{{- if (include "crowd.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    {{- include "crowd.labels" . | nindent 4 }}
type: Opaque
data:
  ATL_JDBC_PASSWORD: {{ .Values.databaseConnection.password | b64enc | quote }}
{{- end }}
