name: Latest Stable Versions
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download RSS
      run: |
        curl -sSO https://my.atlassian.com/download/feeds/confluence.rss
        curl -sSO https://my.atlassian.com/download/feeds/jira-software.rss
    - name: Check Confluence latest version
      id: getxmlcon
      uses: moxbot/get-xml-info@1.0
      with:
        xml-file: 'confluence.rss'
        xpath: '//title[contains(., "Linux")]'
    - name: Check Jira latest version
      id: getxmljira
      uses: moxbot/get-xml-info@1.0
      with:
        xml-file: 'jira-software.rss'
        xpath: '//title[contains(., "Linux")]'
    - name: Update Confluence version
      env:
        CONFLUENCE_VERSION: ${{ steps.getxmlcon.outputs.info }}
      run: |
        scripts/update_chart_version.sh "confluence-server" "$CONFLUENCE_VERSION"
        rm confluence.rss
    - name: Update Jira version
      env:
        JIRA_SOFTWARE_VERSION: ${{ steps.getxmljira.outputs.info }}
      run: |
        scripts/update_chart_version.sh "jira-software" "$JIRA_SOFTWARE_VERSION"
        rm jira-software.rss
    - name: Create Pull Request
      id: cpr
      uses: moxbot/create-pull-request@v2
      with:
        token: ${{ secrets.CR_TOKEN }}
        commit-message: '[Release] update Charts with the latest stable App versions
        committer: moxbot <bot@mox.sh>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: '[Release] latest stable Apps versions'
        body: |
          New versions of the Apps have been released, and the Charts have been updated.
          - PR auto-generated in the repo: [helm-charts][1]

           [1]: https://github.com/javimox/helm-charts
        branch: latest-stable-versions
        labels: update-appVersion
