name: Release Charts

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history and commit message
        run: |
          git fetch --prune --unshallow
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: Configure Git
        run: |
          git config user.name "moxbot"
          git config user.email "bot@mox.sh"

      # See https://github.com/helm/chart-releaser-action/issues/6
      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Add dependency chart repos
        run: |
          helm repo add stable https://kubernetes-charts.storage.googleapis.com/

      - name: Run chart-releaser
        if: "github.event.pull_request.merged == true && contains( env.commitmsg, 'Release' )"
        uses: moxbot/chart-releaser-action@v1.0.0-rc.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
